#! /usr/bin/env python 

import os, re, glob
from argparse import ArgumentParser
from subprocess import call 
import logging
log = logging.getLogger(os.path.basename(__file__))

parser=ArgumentParser()
parser.add_argument('-in','--indir', type=str)
parser.add_argument('-o','--outdir', type=str)
parser.add_argument('-s','--suffix', type=str,default='train')
args=parser.parse_args()

FILE_PATTERN=re.compile(
    '^(?P<prefix>\S+)?'
    '\.(?P<id>\d+)'
    '\.(?P<generator>\w+)'
    '(?P<mode>(ggH)|(VBFH))'
    '(?P<mass>\d+)'
    '(?P<name>\w+)'
    '\.merge'
    '\.(?P<derivation>\w+)'
    '\.(?P<tag>\w+)'
    '\.(?P<suffix>\S+)$')


def rename(f,outdir):
    match = re.match(FILE_PATTERN, f)
    if match:
        dsid = match.group('id')
        mode = match.group('mode')
        mode=mode[:-1]
        mode.lower()
        mass = match.group('mass')
        outname= '_'.join(['reco',mode,mass,args.suffix,'root'])
        of=os.path.join(outdir,outname)
        call('mv %s %s'%(f, of),shell=True)
        
if __name__=='__main__':
    # dirs = os.listdir(args.indir)
    # for d in dirs:
    #     d = d.replace("xAOD", "merge.DAOD_HIGG4D3.NTUP75")
    #     os.system("mkdir -p  %s"%os.path.join(args.outdir, d))

    # cp over the nuples 

    ntups = glob.glob("/home/sbahrase/WorkDesk/SAMPLES/nTUPLEs/xTau75/hh/reco*train.root")
    outdirs = glob.glob("%s/mc15_*"%args.outdir)
    for ntup in ntups:
        name = ntup.split("/")[-1]
        mass = name.split("_")[2]; mode = name.split("_")[1]
        if mode=="vbf": 
            mode ="VBF"
        print mass, mode
        for d in outdirs:
            if "%sH%s"%(mode, mass) in d:
                fname = d.split("/")[-1]+".root"
                os.system("cp %s %s "%(ntup, os.path.join(d, fname)))
    
    
